version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel-app:/var/www
    ports:
      - "9000:9000"
  
  web:
    image: nginx:alpine
    volumes:
      - ./laravel-app:/var/www
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf

networks:
  app-network:

configs:
  nginx-config:
    file: ./nginx/nginx.conf